package br.com.furb.gals;

public interface ScannerConstants
{

    int[] TOKEN_STATE = {-2,  0, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,  8, -2,  8,  8,  8,  8,  8,  8,  8,  8, -2, -2,  2, -2,  8,  8,  8,  8,  8,  8,  8, -2,  5, -2, -2,  3, -2,  8, -2, -2, -2, -2, -2,  8,  8,  8, -2, -2, -2, -2, -2, -2,  8,  8,  8,  8,  8, -2, -2, -2, -2, -2, -2, -2,  8,  8,  8,  8,  8,  8,  8,  8,  8, -2, -2, -2, -2, -2, -2, -2, -2,  4, -2,  8,  7,  7, -2,  8,  8,  8,  8,  8,  8,  8,  8,  6 };

    int[] SPECIAL_CASES_INDEXES =
        { 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4 };

    String[] SPECIAL_CASES_KEYS =
        {  "Bicombustível", "Diesel", "Gasolina", "Álcool" };

    int[] SPECIAL_CASES_VALUES =
        {  10, 11, 12, 9 };

    String[] SCANNER_ERROR =
    {
		"Sequência de símbolos não identificada",
		"",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"Sequência de símbolos não identificada",
		"KM inválido",
		"Sequência de símbolos não identificada",
		"",
		"Motor ou KM inválido",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Valor inválido",
		"KM inválido",
		"",
		"KM inválido",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Valor inválido",
		"",
		"KM inválido",
		"KM inválido",
		"",
		"KM inválido",
		"",
		"Sequência de símbolos não identificada",
		"Placa inválida",
		"Valor inválido",
		"KM inválido",
		"KM inválido",
		"",
		"",
		"",
		"Placa inválida",
		"Placa inválida",
		"Valor inválido",
		"Valor inválido",
		"Valor inválido",
		"KM inválido",
		"",
		"",
		"",
		"",
		"",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Valor inválido",
		"Valor inválido",
		"Valor inválido",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"Placa inválida",
		"",
		"Valor inválido",
		"",
		"",
		"",
		"Valor inválido",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""
    };

}
